### ISSUE TITLE
remove casa de Synset 02913152-n

### ISSUE THREAD

**Issue by vcvpaiva** [arademaker/openWordnet-PT#13]
no momento temos: casa, edifício, edifícios, prédio
Remove casa and edificios, leaving only edifício, prédio.

 Synset 02726305-n

now: Portuguese 	casa, apartamento, aposentos
desired: Portuguese 	 apartamento

Synset 03544360-n
now: Portuguese 	teatro, habitação, casa, Habitações, vivenda, edifícios residenciais, firma
desired: Portuguese 	casa, habitação, vivenda, edifício residencial

Synset 08559508-n
now: Portuguese 	casa, Lar
desired: Portuguese 	casa, lar

Synset 08078020-n
now: Portuguese 	agregado familiar, pessoa da família que mora na mesma casa, casa, família, classe, linhagem
desired: Portuguese   casa, família, lar

Synset 03002816-n
now: Portuguese 	casa, chalé
desired: Portuguese 	 chalé

**Comment by arademaker** [comment]
mudanças já tinham sido aplicadas.
