### ISSUE TITLE
Adding verbs without se to OWN-PT

### ISSUE THREAD

**Issue by vcvpaiva** [arademaker/openWordnet-PT#33]
Missing from OPenWN-PT	Valeria's suggestion for synset
	
1.safar	02074377-v
2.revoltar	02583139-v
3.reafirmar	01011923-v
4.queixar	00907147-v
5.pavonear	02141973-v
6.onerar (only have "onerar com")	NA
7. malograr	NA
8.irradiar	02686952-v
9.intrometer	00780191-v
10.insurgir	02583139-v
11.habituar	00273445-v
12.filiar	02598765-v
13.exaurir	00075021-v
14.escancarar	02718750-v
15.enroscar	01868370-v
16.enamorar	00148597-v
17.empavonar	02141973-v
18.embasbacar	02164531-v
19.desenganar	01798936-v
20.descamar	00009492-v
21.desbocar	00865387-v
22.corresponder	01006810-v
23.contorcer	01868370-v
24.compenetrar	00728954-v
25.assegurar	00890590-v
26.arrepender	01796582-v
27.aproximar	02666060-v
28.apiedar (-se de)	01821996-v
29.aperceber	02106506-v
30.apear	01958452-v
31.apartar	01560984-v
32.amoldar	01560984-v
33.aconchegar	01425348-v

**Comment by arademaker** [comment]
onde colocar, sugestão:

6.onerar (only have "onerar com") NA
7. malograr NA

**Comment by vcvpaiva** [comment]
adicionei nos respectivos synsets.

On Sat, Jan 24, 2015 at 8:13 AM, Alexandre Rademaker <
notifications@github.com> wrote:

> onde colocar, sugestão:
>
> 6.onerar (only have "onerar com") NA
> 7. malograr NA
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arademaker/openWordnet-PT/issues/33#issuecomment-71324651>
> .
>



-- 
Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by arademaker** [comment]
ok obrigado.

**Comment by arademaker** [comment]
see also #61
