### ISSUE TITLE
pressentimento

### ISSUE THREAD

**Issue by vcvpaiva** [arademaker/openWordnet-PT#53]
(with-synset XXXXX
(add "...")
(remove "..."))

(with-synset 07522128-n
(add "pressentimento")
)

**Comment by arademaker** [comment]
Que tal também 

```
(with-synset 07522128-n
	   (add "premonição"))
```
??

**Comment by vcvpaiva** [comment]
pode ser sim.

premonição ja esta' em

05919034-n
<http://compling.hss.ntu.edu.sg/omw/cgi-bin/wn-gridx.cgi?usrname=&gridmode=grid&synset=05919034-n&lang=por&lang2=eng>

mas acho que essa nao modifica o shape da rede.

On Thu, Jan 1, 2015 at 7:09 AM, Alexandre Rademaker <
notifications@github.com> wrote:

> Que tal também
>
> (with-synset 07522128-n
>        (add "premonição"))
>
> ??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arademaker/openWordnet-PT/issues/53#issuecomment-68488693>
> .
>



-- 
Valeria de Paiva
http://www.cs.bham.ac.uk/~vdp/
http://valeriadepaiva.org/

**Comment by vcvpaiva** [comment]
07179342-n ✪ 'an accommodation in which both sides make concessions';
(with-synset 07179342-n
(add "conchavo")
)
conchavar/conchavo nao estao mesmo na OWN-PT

(with-synset XXXXX
(add "...")
(remove "..."))

**Comment by vcvpaiva** [comment]
02303331-v 'lose (s.th.) or lose the right to (s.th.) by some error, offense, or crime'
1. give up , forfeit2  , throw overboard , waive  , forgo , forego 
(with-synset 02303331-v
(remove "prevaricação")
(remove "penalidade"))

2. 00741925-n 'wrongful conduct by a public official'; 
(with-synset 00741925-n
(add "prevaricação")
(remove "Prevaricação"))
nao sei porque ou como mas 00741925-n tem Prevaricação duas vezes.

**Comment by arademaker** [comment]
Não entendi as modificações no 02303331-v. Agora ele tem "perder" "renunciar" "privar-se" apenas, vc pede para remover ou adicionar "prevaricação" e "penalidade"?

Sobre 00741925-n rodei
```
(with-synset 00741925-n
	   (remove "Prevaricação")
	   (remove "Prevaricacão")
	   (add "prevaricação")) 
```

Sobre "mas acho que essa nao modifica o shape da rede" gostaria de entender melhor para melhor definir nossos guidelines. Qual sua intuição sobre o que muda e não muda o shape da rede? O que seria este "shape"  da rede?

**Comment by vcvpaiva** [comment]
hmm, acho que voce ja' tinha consertado  o synset 02303331-v  que 'e de verbo e nao pode ter substantivos como "prevaricação" e "penalidade" que aparecem na interface no momento.
>Sobre 00741925-n rodei
e' isso mesmo, eu nao tinha visto a cedilha em uma versao de Prevaricacao com maiuscula.

>Qual sua intuição sobre o que muda e não muda o shape da rede?
a minha intuicao 'e que se um significado esta' faltando e a gente adiciona, nao mudamos o "shape da rede", nao introduzimos ou confundimos os links que existems entre os synsets que ja estao la. "premonicao" e' uma palavra erudita que ou so' tem um significado ou os que tem sao bem proximos uns dos outros e portanto nao mudam os "clusters" de significados que temos.

mas nos verbos de emocao os algoritmos do Gerard fizeram algumas emocoes mais proximas de outras. a gente consegue ver que horrorizar=horrify 'e muito mais forte do que consternar, mas se voce adionar 'consternar' ao synset de 'deprimir', apesar dos significados serem proximos, vc esta' mudando o que os algoritmos acharam que eram as coisas mais proximas e eu nao sei se isso faz sentido ou nao. esse criterio, como todos os outros que inventamos pra nos mesmos, precisa ser descoberto ao tentar fazer a tal limpeza/melhoria. pois muitas vezes a gente nao se da' conta de significados que existem, mas nao sao os mais obvios. por exemplo eu pedi pra tirar `lua' de dois synsets que acho que correspondem a month=mes. mas a gente tb fala  em portugues que "muitas luas se passaram..."
o WN tem um tanto de significados metaforicos, que sao mais complicados mesmo.

e sim, o "shape of the net" e' o clustering de significados que o processo de machine learning to Gerard "descobriu". ele esta' errado em algumas coisas, mas em outras, onde gente nao tem criterios claros, 'e o melhro que podemos fazer.

**Comment by arademaker** [comment]
tudo já foi concertado nos dados na ultima interface.
