### ISSUE TITLE
substantivo: sequenciador

### ISSUE THREAD

**Issue by vcvpaiva** [arademaker/openWordnet-PT#55]
(with-synset XXXXX
(add "...")
(remove "..."))
04173511-n 'an apparatus that can determine the sequence of monomers in a polymer';
(with-synset 04173511-n
(add "sequenciador")
)

04173344-n 'computer hardware that sorts data or programs into a predetermined 
(with-synset 04173344-n
(add "sequenciador")
)

**Comment by arademaker** [comment]
done
